### ISSUE TITLE
Example throws Error

### ISSUE THREAD

**Issue by Thomasillo** [collinsmuriuki/simple_cache#3]
The very first example presented in the README doesn't work for me.

Steps to reproduce:
1. create blank project using `cargo new`
2. copying the `[dependencies]` section from the README into the Cargo.toml
3. copying the very first code snippet (with the fibonacci function) into src/main.rs
4. running cargo run
5. fails

```$ cargo run
...
    Finished dev [unoptimized + debuginfo] target(s) in 1m 00s
     Running `target/debug/stuff`
thread 'main' panicked at src/main.rs:3:1:
already borrowed: BorrowMutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I did not change a single letter in the code example..

**Comment by c12i** [comment]
Hi @Thomasillo thanks for catching this bug. The `BorrowMutError` results from calling `borrow_mut` more than once for each recursive call. I am providing a fix for this in an upcoming PR
